version: "3.8"
services:
  localstack:
    container_name: "aws-s3"
    image: localstack/localstack
    ports:
      - "192.168.0.197:4572:4572" # external service port range
      - "192.168.0.197:4566:4566" # LocalStack Edge Proxy
      - "127.0.0.1:4572:4572" # external service port range
      - "127.0.0.1:4566:4566" # LocalStack Edge Proxy
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
